### ISSUE TITLE
Clear error message if exec:exec is configured and the user uses "mvn exec:java" instead

### ISSUE THREAD

**Issue by ge0ffrey** [mojohaus/exec-maven-plugin#10]
We 'd like to use "mvn exec:exec" to easily run the examples of our open source project (optaplanner.org), but our users expect to be using "mvn exec:java".
When they use "exec:java", it's currently impossible to get the maven-exec-plugin to output something like "Please use exec:exec instead!". Instead, they get some weird classpath issue, spend a few hours debugging that, start complaining about how our examples don't just work out of the box as advertised, etc. In short, it causes a lot of unnecessary grief.

**Comment by khmarbaise** [comment]
Just taken a look very short look on the web site and docs and found:

```
$ cd optaplanner-examples
$ mvn exec:java
```

May be i misunderstand your request but based on that i would use `exec:java` and not `exec:exec`?

May be you can elaborate a little bit more what the problem is?

**Comment by ge0ffrey** [comment]
Can you also try doing "mvn exec:exec" on that repository. You'll get an error message, but it won't say "please use mvn exec:java instead."

The problem is that our users don't read our documentation, so they do exec:exec instead of exec:java. We actually want to use exec:exec (so the jvm heap size can be overwritten from the command the line), but then even more users do exec:java instead of exec:exec (we had it like that for a while).

When a user uses exec:exec instead of exec:java, they don't realize it (even Java guru's). Instead, they start figuring out what's wrong in the pom.xml configuration, etc. Or simply give up, because it doesn't "just work" out of the box.

**Comment by ge0ffrey** [comment]
See also
  https://issues.jboss.org/browse/PLANNER-287 (due to this one we switched from exec:exec to exec:java - it was easier to switch then to educate our users to use exec:exec because I tried that for months)
  https://issues.jboss.org/browse/PLANNER-404 (due to this one we want to switch back to exec:exec....)

**Comment by khmarbaise** [comment]
As i mentioned before it sounds like you should provide appropriate scripts to handle this if your users don't read documentations.....Furthermore If you call one goal of a plugin which is not intended for the purpose why should it produce a message please use the other goal...apart from that how should it identify in which cases such kind of error message would make sense? 
One other things is: The referenced tickets show me that exec-maven-plugin is not the right way to go...butter created separate scripts (via appassembler-maven-plugin) which can handle that in a very convenient way...

**Comment by ge0ffrey** [comment]
We got scripts doing this for the assembly zip.
But we also have users building from source, and they use exec:exec to avoid having to do a -Dfull build which takes very long.

**Comment by khmarbaise** [comment]
Why do you need scripts for creation of assembly zip?...If a user is building from source it would be worth to think about a separations of the examples into a separate project and create appropriate scripts for that...Of if you like you could create an appropriate PR to solve the issue with exec-maven-plugin...BTW: How long is in your case `very long` build time?

**Comment by ge0ffrey** [comment]
+1 that creating a PR is probably the best way forward for me to explain
what I mean.

Here's the example on which mvn exec:exec or exec:java is used if users
change the example sources:
  https://github.com/droolsjbpm/optaplanner/tree/master/optaplanner-examples

Here's the distribution zip assembly's script that is used for those that
don't build the examples from source:

https://github.com/droolsjbpm/optaplanner/tree/master/optaplanner-distribution/src/main/assembly/scripts

A -Dfull build takes about 5 minutes (javadocs, distro zips, ...) and that
will only get worse.

2015-11-22 11:31 GMT+01:00 Karl Heinz Marbaise <notifications@github.com>:

> Why do you need scripts for creation of assembly zip?...If a user is
> building from source it would be worth to think about a separations of the
> examples into a separate project and create appropriate scripts for
> that...Of if you like you could create an appropriate PR to solve the issue
> with exec-maven-plugin...BTW: How long is in your case very long build
> time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojohaus/exec-maven-plugin/issues/10#issuecomment-158743745>
> .
>



-- 
With kind regards / Met vriendelijke groeten,
Geoffrey De Smet

**Comment by ge0ffrey** [comment]
@khmarbaise This still bites us. If I send in a good PR for this issue, will you accept it?

Here's what I would send in as a PR:

- Add a new configuration parameter "acceptedGoal", which is an enum with options "java", "exec", "all". The default would be "all" for backwards compatibility
- If the acceptedGoal is "java" and "mvn exec:exec" is called it fails fast with an error message "The goal exec:exec is not accepted on this pom: only the goal exec:java is allowed for this pom."
- If the acceptedGoal is "exec" and "mvn exec:java" is called it fails fast with an error message "The goal exec:java is not accepted on this pom: only the goal exec:exec is allowed for this pom."
