### ISSUE TITLE
`mexec-86` integration test fails at TravisCI

### ISSUE THREAD

**Issue by kevstigneev** [mojohaus/exec-maven-plugin#112]
`mexec-86` integration test consistently fails at TravisCI with the following outout:

    [INFO] Building: mexec-86/pom.xml
    [INFO] run script verify.groovy
    [INFO] ..FAILED (6.0 s)
    [INFO]   The post-build script did not succeed. expected:<5> but was:<6>

Looks like it's something specific to the build environment because nobody has reproduced it locally - it just succeeds.

All TravisCI builds since Feb 26 2018 failed due to that. It affected PRs #95, #96, #97, #98, #100, #104, #110.

**Comment by rfscholte** [comment]
Not an issue anymore, both https://travis-ci.org/mojohaus/exec-maven-plugin and https://ci.appveyor.com/project/khmarbaise/exec-maven-plugin are green again
