### ISSUE TITLE
Nothing logged when command fails

### ISSUE THREAD

**Issue by paulmillar** [mojohaus/exec-maven-plugin#12]
The exec-maven-plugin fails, nothing is logged except that it FAILED.

The following is an example of such a failure:

```
[INFO] Building dCache FHS layout 2.14.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ dcache-fhs ---
[INFO] Deleting /scratch/jenkins/jenkins/workspace/dCache-v2.14/packages/fhs/target
[INFO] 
[...]
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:exec (default) @ dcache-fhs ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Logback config for building and testing ............ SUCCESS [  8.986 s]
[...]
[INFO] dCache FHS layout .................................. FAILURE [ 12.816 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17:27 min
[INFO] Finished at: 2015-11-18T19:42:24+01:00
[INFO] Final Memory: 131M/241M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (default) on project dcache-fhs: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

This makes it impossible to diagnose the problem from this information alone.  To understand the failure, one must re-run maven with the -X option, which produces diagnostic information so the exact command is discoverable.  Running this command can then reproduce the problem, so discovering the underlying cause.

I would expect that, if the command has failed, the output from stdout and stderr are presented in the log file, along with the command that failed.

Cheers,

Paul.

**Comment by khmarbaise** [comment]
Can you please check if this fit's your needs...

**Comment by paulmillar** [comment]
Does the output from stdout and stderr get logged too? 

From a casual inspection of the patch, it seems it adds support for logging the failed command, but not stdout and stderr.  While this is certainly useful information, it would be nice to also know why the command failed.

Usually the last few lines (the last 10..15, say) lines of stdout and stderr usually contain enough information to describe the problem.

**Comment by binmahone** [comment]
hi 

I met similar issues in 1.4.0, is it resolved in 1.5.0 or is it a won't-fix?
Actually I don't understand why skipping the stdout and stderr when the command fails.
can someone kindly elaborated? thanks!

**Comment by paulmillar** [comment]
The patch that closed this issue updates the plugin to show the command that was run and the resulting return-code, if that command returned a non-zero return-code.

I cannot say whether this is a WONT_FIX on logging stdout and stderr, or simply a misunderstanding of what was requested.

I, too, would have preferred to see the stdout/stderr, but seeing the command line and the return-code is at least a step forward.

I have no strong opinion on whether stdout and stderr should be logged if there is no problem (i.e., a return-code of 0), but they should be logged if the command fails (i.e., returns a non-zero return-code).

**Comment by khmarbaise** [comment]
What about offering an patch for that ?

**Comment by paulmillar** [comment]
Fair comment.  I'm happy to have a go, if that approach would be appreciated.

**Comment by khmarbaise** [comment]
Would be great. But let use create a separate issue for that.
