### ISSUE TITLE
Add Documentation for Configuration Options

### ISSUE THREAD

**Issue by SwingGuy1024** [mojohaus/exec-maven-plugin#149]
I can't find any documentation for the options available in the Configuration tag. For example, I was getting error messages when I exited my application telling me that three threads had failed to shut down after 15 seconds. My IDE showed me that there were plenty of tags available like keepAlive, killAfter, daemonThreadJoinTimeout, skip, and plenty of others, but I couldn't find any documentation of what these could be used for or how to use them. I looked on this gitHub project and at https://www.mojohaus.org/exec-maven-plugin, but I couldn't find anything. I needed to use trial and error to figure out that keepAlive required a boolean value rather than a numerical timeout, and to learn that it's deprecated. After trying a few others, I finally stumbled across cleanupDaemonThreads and set it to false, which solved my problem. But some documentation for all configuration options would be appreciated.

**Comment by rfscholte** [comment]
Documented is generated. You need to choose the goal at mojohaus.org/exec-maven-plugin/plugin-info.html and you'll see all the options. 
Almost every maven plugin webpage has a generated page for this just look for the `goals`
