### ISSUE TITLE
System.out.print not working

### ISSUE THREAD

**Issue by quantrpeter** [mojohaus/exec-maven-plugin#154]
Hi
   I use below command to run my java:

mvn -Dexec.args="-classpath %classpath hk.quantr.riscv_simulator.Simulator" -Dexec.executable="C:\Program Files\Java\jdk-13.0.2\bin\java.exe" -Dexec.classpathScope=runtime -Dmaven.ext.class.path="C:\Program Files\NetBeans-11.3\netbeans\java\maven-nblib\netbeans-eventspy.jar;C:\Program Files\NetBeans-11.3\netbeans\java\maven-nblib\netbeans-cos.jar" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.5.0:exec

My code System.out.print("+"); wont print anything on screen, even i execute System.out.flush(), please help
thanks
Peter

**Comment by khmarbaise** [comment]
Ah sorry oversight that there is a link to "transfer issue." Thanks Anders

**Comment by quantrpeter** [comment]
thanks Gentlemen
