### ISSUE TITLE
3.0.0 release notes?

### ISSUE THREAD

**Issue by mirabilos** [mojohaus/exec-maven-plugin#156]
Where are the release notes? Is this even a release intended for public consumption? Even the [plugin homepage](https://www.mojohaus.org/exec-maven-plugin/) still says 1.6.0 is latest… and the tagging was done by a contributor, not the maven-release-plugin, so it looks fishy…

**Comment by mirabilos** [comment]
@olamy @mkarg @khmarbaise ?

**Comment by khmarbaise** [comment]
What do you think about https://github.com/mojohaus/exec-maven-plugin/releases/tag/exec-maven-plugin-3.0.0 ?

**Comment by mkarg** [comment]
Why not mentioning https://github.com/mojohaus/exec-maven-plugin/commit/7c8c61fc4374992e0e461c53b0d768192b5b0d26 (<timeout>) as a new feature?

**Comment by khmarbaise** [comment]
Ah was not assigned to the milestone...and marked as enhancement. Done.

**Comment by khmarbaise** [comment]
So rechecked and updated release notes.

**Comment by mirabilos** [comment]
Karl Heinz Marbaise dixit:

>What do you think about
>https://github.com/mojohaus/exec-maven-plugin/releases/tag/exec-maven-plugin-3.0.0

This looks like an automatically created tag from the release process.
It could be accidental, given the release was done by a user (not a CI
system), was not announced anywhere and the plugin homepage still lists
1.6.0 as latest version, so it might well be a beta/snapshot thing that
accidentally was released with a normal version number.

Also, for a double-major update, we need release notes to see whether
we’re affected by any breaking changes.

**Comment by mirabilos** [comment]
I’m looking for something like [this](https://blogs.apache.org/maven/entry/apache-maven-compiler-plugin-version1) by the way.

**Comment by khmarbaise** [comment]
@mirabilos The release tag is based on a user based release process (maven-release-plugin based) from a users machine which is producing a release tag which is done by member of mojohaus and that is **NOT** fishy.

I have added manually the release notes information to the tag.

Apart from that all plugins on Mojohaus will be released by users not from a CI system. 

There had been a [VOTE about the release ](https://groups.google.com/forum/#!topic/mojohaus-dev/B2RFx4SBUqA).

The formal release announcement has not being made ([could be done done here](https://groups.google.com/forum/#!forum/mojohaus-dev)).  (Done in the meantime https://groups.google.com/forum/#!topic/mojohaus-dev/3_1vRlMjahk).

The blog you have linked is is of the Apache Software Foundation which can't being used cause this is MojoHaus which is not part of the Apache Software Foundation.

And yes the homepage shows currently 1.6.0 cause the page has not being updated/published yet with released version. (Im the meantime I have updated the homepage).

Apart from that it is not an [beta/snapshot version ](https://search.maven.org/artifact/org.codehaus.mojo/exec-maven-plugin).

Furthermore this is an open source project if you like to have more detailed release notes we are open for pull requests.

**Comment by mirabilos** [comment]
Karl Heinz Marbaise dixit:

>@mirabilos The release tag is based on a user based release process
>@(maven-release-plugin based) from a users machine which is producing a
>@release tag which is done by member of mojohaus and that is **NOT**
>@fishy.

Of course this may be, but I have (had) no way of knowing this.

>I have added manually the release notes information to the tag.

Thanks.

>Apart from that all plugins on Mojohaus will be released by users not
>from a CI system.

OK. Thanks for the information.

>The formal release announcement has not being made ([could be done done
>here](https://groups.google.com/forum/#!forum/mojohaus-dev)). (Done in
>the meantime
>https://groups.google.com/forum/#!topic/mojohaus-dev/3_1vRlMjahk).

Thank you. Much appreciated.

>The blog you have linked is is of the Apache Software Foundation which
>can't being used cause this is MojoHaus which is not part of the Apache
>Software Foundation.

OK, but “something along the lines”, something that can be found.
I am aware not all plugins are from them, but others I know also
published release announcements/notes, and I could not find one
for this.

>And yes the homepage shows currently 1.6.0 cause the page has not being
>updated/published yet with released version. (Im the meantime I have
>updated the homepage).

Thank you!

>Apart from that it is not an [beta/snapshot version

I had, again, no way of knowing that. With all the other suspect
things, this could have been a mis-numbered beta/snapshot version.

>Furthermore this is an open source project if you like to have more
>detailed release notes we are open for pull requests.

That would require me to know what goes on in this project. I’m
not a Java person and already active in way too many other projects
(Debian, a BSD, and numerous smaller ones, including musical, shell,
editor, system utilities, etc.) so I wouldn’t know, but a developer
of the project would.
