### ISSUE TITLE
Add retry capability

### ISSUE THREAD

**Issue by jbennett2091** [mojohaus/exec-maven-plugin#174]
I'd like to see a retry capability added to exec:exec.  Default value can be 1 (for backward compatibility).

We have a multi-module maven build, where one of the submodules uses grails and necessitates invoking grails from maven via exec:exec.  Unfortunately, this portion of the build is a bit dodgy and fails intermittently, generally succeeding when run a second time - we assume a flaky test, but let's not go there.  Currently, unfortunately, when exec fails it brings the whole hour-long build down with it.

While the above is specific to our own use, I am guessing others would benefit from a retry capability.

**Comment by bmarwell** [comment]
Hey, any way you could execute a script instead?
If so, you could use something like 

```sh
#!/bin/bash
gradle "$args" || gradle "$args"
exit $?
```

But yeah, I see the point of this feature request. Can you create a PR for this?
