### ISSUE TITLE
exec:exec goal fails on cli because it requires dependency resolution TEST

### ISSUE THREAD

**Issue by Buuhuu** [mojohaus/exec-maven-plugin#184]
Hi, 

I am trying to use the `exec:exec` goal in order to get a list of all modules in a build reactor:

```
- pom.xml (com.my:project:1.0.0-SNAPSHOT)
- sub1
-- pom.xml (com.my:sub1:1.0.0-SNAPSHOT)
- sub2
-- pom.xml (com.my:sub2:1.0.0-SNAPSHOT with dependency to sub1)
```

Running the following goal as suggested by https://stackoverflow.com/a/51824145 unfortunately fails because the com.my:sub1:1.0.0-SNAPSHOT dependency cannot be resolved in sub2, when there has not been an `install` into the local repository first.

```
mvn exec:exec -Dexec.executable=echo -Dexec.args=\${project.groupId}:\${project.artifactId}
```
The reason of that is that the [ExecMojo](https://github.com/mojohaus/exec-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/exec/ExecMojo.java#L82) requires dependency resolution scope TEST. What is the reason for that? 

I managed to get this use case working by setting the scope to NONE (the default)

**Comment by bmarwell** [comment]
Please post your exec configuration as well using Markdown code tags, thanks.
