### ISSUE TITLE
Build 15-ea uses JDK 16 now, not JDK 15

### ISSUE THREAD

**Issue by dmatej** [mojohaus/exec-maven-plugin#208]
Java version: 16.0.1, vendor: Azul Systems, Inc., runtime: /opt/hostedtoolcache/jdk/16.0.1/x64

https://github.com/mojohaus/exec-maven-plugin/runs/2486107159?check_suite_focus=true
https://github.com/mojohaus/exec-maven-plugin/blob/master/.github/workflows/maven.yml

**Comment by slachiewicz** [comment]
Fixed thx
