### ISSUE TITLE
java.nio.file.NoSuchFileException: compile-xilogs.txt.lck

### ISSUE THREAD

**Issue by vuvgaG** [mojohaus/exec-maven-plugin#214]
![image](https://user-images.githubusercontent.com/75189112/126026569-d261aecf-a1de-40cf-9dbf-5032c0e6ad26.png)

macOS 11.4
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
-> % mvn --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"

**Comment by dmatej** [comment]
This doesn't look like an issue of the plugin, but rather of some logging configuration of the project under the package `com.snowdon.dev`.
