### ISSUE TITLE
Multiple execution of plugin does not work

### ISSUE THREAD

**Issue by yannislionis** [mojohaus/exec-maven-plugin#22]
I tried implementing multiple plugin execution as described here: http://article.gmane.org/gmane.comp.java.maven-plugins.mojo.user/1307

I get an error:
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (default-cli) on project hsbc.ui.apps: The parameters 'executable' for goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec are missing or invalid -> [Help 1]

It seems the configuration block needs to live outside of the executions block. Is the FAQ incorrect (I can see it is old) and can this be done? Note that I need to execute two different executables.

**Comment by khmarbaise** [comment]
Can you show your pom file which you are using for this?

**Comment by yannislionis** [comment]
Sure, here it is:

        <profile>
            <id>runNpmAndGrunt</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>1.4.0</version>
                        <executions>
                            <execution>
                                <id>npm install</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>npm</executable>
                                    <workingDirectory>${project.basedir}/build</workingDirectory>
                                    <arguments>
                                        <argument>install</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>gulp build</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>npm</executable>
                                    <workingDirectory>${project.basedir}/build</workingDirectory>
                                    <arguments>
                                        <argument>install</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

**Comment by khmarbaise** [comment]
`org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (default-cli)` this shows me that you are trying to call exec plugin via:
`mvn exec:exec ...` which means you need to give the parameters on command for Maven which will *not* use the things you have defined in your pom file...If you like to define defaults for calling exec-maven-plugin via `mvn exec:exec ...` you need to use the appropriate id which is `default-cli` which mean in other words that you can define only a single configuration which is used for command line calling. If you are using Maven 3.3.X you can define several configurations which you can also address on command line via:

    mvn exec:exec@first-config ....
   
This can [found in the release notes](http://maven.apache.org/docs/3.3.1/release-notes.html) for Maven 3.3.1...

If you like to bind exec-maven-plugin in your life cycle you need to call maven with a life cycle like:

    mvn package 

for example....

**Comment by yannislionis** [comment]
You are absolutely correct, I was using mvn exec:exec simply to save time by not running the rest of the maven build - the intention was always to run mvn package. It never occurred to me that the behaviour would be different.

Works a treat now, thank for your help.

**Comment by khmarbaise** [comment]
BTW: All the parts of the configuration which are identical to all executions can be moved to the plugin level...that makes pom files shorter...(and follows DRY)...
