### ISSUE TITLE
exec-maven-plugin yarn打包vue项目 

### ISSUE THREAD

**Issue by sxh-netizen** [mojohaus/exec-maven-plugin#231]
exec-maven-plugin yarn打包vue项目 ，不会出现app_config.js
![image](https://user-images.githubusercontent.com/58098910/133725123-31dd979c-b8d3-4c69-8fc8-3f06dbce8ac7.png)
这是正常打包的结构
![image](https://user-images.githubusercontent.com/58098910/133725216-5387dc15-4286-4f6a-b447-50b889a7fb2c.png)

**Comment by sxh-netizen** [comment]
这是我的maven配置
![image](https://user-images.githubusercontent.com/58098910/133725300-64eec83e-94a7-49df-9bc0-ee75f22a2b20.png)
![image](https://user-images.githubusercontent.com/58098910/133725306-def316d2-b913-4678-95a8-f291f8d47d3a.png)

**Comment by bmarwell** [comment]
Please post your messages in the english language, thank you.

Please add your configuration using Markdown code, not as an image.

for executing yarn, I can recommend the [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin)
