### ISSUE TITLE
<classpath/>  doesn't work well in 3.0.0, the latest version in maven repository 

### ISSUE THREAD

**Issue by wellzz** [mojohaus/exec-maven-plugin#266]
specialArg is updated only when `isLongModulePathArgument( specialArg ) || isLongClassPathArgument( specialArg )` returns true,
but it can't because specialArg's default value is null.
I find that this issue has been fixed in master branch. 
when do we release the next version?

https://github.com/mojohaus/exec-maven-plugin/blob/9705839246711bd375bf7712df05c621b168fbb1/src/main/java/org/codehaus/mojo/exec/ExecMojo.java#L675

**Comment by maartenc** [comment]
We face the same issue. So far, we didn't find a workaround, which makes that we cannot use this plugin right now 😢 
It would be great if a new version of this plugin could be released.

**Comment by slawekjaranowski** [comment]
ping me in a week, you can also drop a line on dev list 😄 

Can you link PR / commit which fix it?

**Comment by maartenc** [comment]
Thank you for your answer @slawekjaranowski 
The PR that fixed this issue was #172

**Comment by slawekjaranowski** [comment]
We have plan to release at next weekend.
Any test of current version will be appreciated before release.

I close it as fixed

**Comment by maartenc** [comment]
Thanks @slawekjaranowski : I did a quick test with the current code (master branch) and verified that it solved this issue.

**Comment by maartenc** [comment]
You can probably close #173 as well 😃
