### ISSUE TITLE
maven iterator plugin is giving class not found exception.

### ISSUE THREAD

**Issue by vamsi523** [mojohaus/exec-maven-plugin#27]
my pom.xml is maven iterator plugin is , i added required dependency also . still i am getting class not Found exception  give me the solution . 

<plugin>
      <groupId>com.soebes.maven.plugins</groupId>
      <artifactId>iterator-maven-plugin</artifactId>
      <version>0.3</version>
      <executions>
        <execution>
         <id>Main</id>
         	<phase>generate-sources</phase>

          <goals>
            <goal>iterator</goal>
          </goals>
          <configuration>
            <items>
               <item>${projec.basedir}/ex.list,${iproject.basedir}/../build/object-src,DATA</item>
          	      </items>
            <pluginExecutors>
              <pluginExecutor>
              	 <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                	<artifactId>exec-maven-plugin</artifactId>
                	<version>1.3</version>
             	</plugin>
                <goal>java</goal>
                <configuration>
               		 <includeProjectDependencies>true</includeProjectDependencies>
                	 <includePluginDependencies>true</includePluginDependencies>
                     <mainClass>com.Main</mainClass>
                    <arguments>
                     <argument>@item@</argument>
                    </arguments>
                </configuration>                
              </pluginExecutor>
            </pluginExecutors>
          </configuration>
        </execution>
      </executions>      
    </plugin>

**Comment by khmarbaise** [comment]
This issue should be put into https://github.com/khmarbaise/iterator-maven-plugin
