### ISSUE TITLE
Redundent -classpath argument issue when using longClasspath

### ISSUE THREAD

**Issue by plcarmel** [mojohaus/exec-maven-plugin#274]
I know this is a duplicate of #93 , but it doesn't seem to get any attention, maybe because it is  a regression and the issue has been closed.

PR: #228

**Comment by plcarmel** [comment]
@slachiewicz , thank you for merging my PR, however...

Since it was an old PR of mine and it got merge quickly, I got paranoid and checked it again to make sure it was fine.

My PR does nothing... there is already a continue at the end of the first if 🤦‍♂️

I think the problem has really been fixed in #172. It's just that since there has been no release, I tricked myself into thinking my little random change fixed the issue.

**Comment by plcarmel** [comment]
Revert (to make it clear that the commit doesn't do what the title says it does: #274

Sorry again for the noise

**Comment by slachiewicz** [comment]
Thx!
