### ISSUE TITLE
how to execute maven exe plugin in parent pom 

### ISSUE THREAD

**Issue by vamsi523** [mojohaus/exec-maven-plugin#28]
I have a maven exec plugin which execute main class with arguments in child its executed successfully  , while i am putting in parent pom mentioning child as a module , it is not executing maven exec plugin and it is not finding out the arguments 
arguments lists are 
<arguments>
<argument>ex.list</argument>
</arguments>

**Comment by khmarbaise** [comment]
This sounds familiar...same as #27 ?

**Comment by khmarbaise** [comment]
No feedback etc.
