### ISSUE TITLE
The parameter 'executable' is missing or invalid

### ISSUE THREAD

**Issue by fendo8888** [mojohaus/exec-maven-plugin#287]
```
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>execute</id>
                        <phase>package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>${project.basedir}/show.bat</executable>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default-cli) on project faas-mall-addons: The parameter 'executable' is missing or invalid -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

进程已结束，退出代码为 1

OK, the parameter setting is wrong

```
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>execute</id>
                        <phase>package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>${project.basedir}/show.bat</executable>
                </configuration>
            </plugin>
```

**Comment by bmarwell** [comment]
Interesting. It should work both ways. Can you create a sample project?

**Comment by pzygielo** [comment]
> OK, the parameter setting is wrong

https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_executions_Tag

-----

The parameter in first example is for execution with **execute** id only.

This
```
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default-cli)
```
shows that execution id was not specified in command line (_default-cli_ is used) - so the configuration as defined in first snippet **is not used**. And there is no other `executable` defined there.

Forcing execution id with `@`, for example
```
mvn exec:exec@execute
```
will use configuration defined in specific (here - with id `execute`) execution.

**Comment by bmarwell** [comment]
Good catch! Maybe you inherited some configuration?? Or what is your command line?
