### ISSUE TITLE
Maven exec plugin execution stopped at parent pom

### ISSUE THREAD

**Issue by vamsi523** [mojohaus/exec-maven-plugin#29]
Below lines are stopped in maven exec plugin and it is working fine in running child , can any one knows 

[DEBUG] Setting accessibility to true in order to invoke main().
Invalid source file ex.list

**Comment by khmarbaise** [comment]
Without a full working example it's really hard to guess what's wrong...

**Comment by khmarbaise** [comment]
Unfortunately no feedback.
