### ISSUE TITLE
EnvStreamConsumer should limit split

### ISSUE THREAD

**Issue by ssiegel95** [mojohaus/exec-maven-plugin#30]
Line 31 of https://github.com/trustin/exec-maven-plugin/blob/master/src/main/java/kr/motd/maven/exec/EnvStreamConsumer.java probably should use the limit option. At present, any environment variables have the '=' character as part of their valid value will not get parsed correctly. For example:

PYSPARK_SUBMIT_ARGS="--master yarn --conf some.spark.setting=somevalue"

The current code:
String[] tokens = StringUtils.split( line, "=");     

will yield a String array of size 3: ['PYSPARK_SUBMIT_ARGS', '--master yarn --conf some.spark.setting', 'somevalue'].

At present, the code will only accept any array of size 2 before it maps values.
Simply limiting the split as follows should take care of the issue:
String[] tokens = StringUtils.split( line, "=", 2);

At very least, the code probably should be much noisier about it rejecting a KEY,VALUE pairs b/c VALUE happens to have a '=' character in it.

**Comment by slawekjaranowski** [comment]
Should be fixed by: #97
