### ISSUE TITLE
Doing several invocations through exec:java?

### ISSUE THREAD

**Issue by jkesselm** [mojohaus/exec-maven-plugin#388]
I need to call the same Java program with several different sets of parameters.

I can't replicate the whole `<plugin>` block because that's a declaration and must be unique.

Maven tells me I can't have multiple `<configuration/>s`. I can have multiple` <executions/>`, but your example puts all the` <arguments/>` in the `<configuration/>` so that doesn't seem to help me.

Can't imagine that there isn't a standard way to do this, but I'm not sure what it is. Possible it's a standard Maven idiom that I just haven't learned yet... but even so it might be a good thing to explicitly document.

**Comment by jkesselm** [comment]
.... Oh. Default configuration outside the executions, then a configuration inside each execution to set local parameters. Yeah, the idiot hadn't yet learned the idiom.

**Comment by kriegaex** [comment]
@jkesselm: For me, this works locally. Can you please share a link to a full reproducer, so other people or I can take a closer look?

**Comment by jkesselm** [comment]
- Clone https://github.com/apache/xalan-java. 
- Check out and switch to branch 'exec-maven-plugin-problem'
- Run `mvn package`. 
- Then look in target/tmp/site. 

You'll see that the xsltc subdirectory has been created, but not target/tmp/site/xalan or target/tmp/site/design. Apparently only the first <execution> is running.

Platform is Fedora running under WSL. `mvn -version` reports 
```Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /mnt/c/users/keshlam/apache-maven-3.6.3
Java version: 1.8.0_382, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.382.b05-2.fc37.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.90.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"```

(Yes, I'm deliberately using a downlevel JDK, to ensure backward compatibility. That shouldn't affect this, right?)

Let me know if you need other details or experiments performed.

-----
Context: What I'm trying to do is move the logic now in stylebook_docgen.sh into the Maven build, so it doesn't have to be done as postprocessing.  As written there it does what's expected (though that's outputting directly to target/site rather than to target/site/tmp). But maven is currently giving me only that one execution of stylebook. I *must* be missing something obvious...

**Comment by jkesselm** [comment]
Checked out the `xalan-java-mvn-refactored` branch.

Added the multi-execution I originally quoted to the POM, directly above `</plugins>`.

Ran the maven build, both just as `package` and as 'clean package site source:jar source:test-jar`.
Either way, `./target/tmp/site/` contains only `xsltc/`. 
Problem confirmed as still present.
 
Output of `mvn -X package` attached. You'll see that there's only one `[DEBUG] Invoking`. So, yes, I'm only getting one of the three executions.

[jkesselm-issue-388.log](https://github.com/mojohaus/exec-maven-plugin/files/13285094/jkesselm-issue-388.log)

**Comment by jkesselm** [comment]
I've updated the `exec-maven-plugin-problem` branch if you want to run it locally.

**Comment by slawekjaranowski** [comment]
I tried ... with xalan on branch exec-maven-plugin-problem  

```
commit 9c47e6f74de2ee834c09fbc860653bf36f38c2da (HEAD -> exec-maven-plugin-problem, origin/exec-maven-plugin-problem)
```

and I have

```
$ mvn package

INFO] --- exec:3.1.0:java (Stylebook XSLTC documentation) @ xalan-project ---
[StyleBook] Overriding loaderConfig="sbk:/style/loaderdesign.xml" (Old="sbk:/style/loader.xml")
[StyleBook] Overriding targetDirectory="./target/tmp/site/xsltc/" (Old=".")
[StyleBook] Caught java.io.IOException
java.io.IOException: Style File/Directory not found
	at org.apache.stylebook.URLHandler.<init>(Unknown Source)
	at org.apache.stylebook.StyleBook.<init>(Unknown Source)
	at org.apache.stylebook.StyleBook.main(Unknown Source)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by jkesselm** [comment]
Sorry, forgot to check that in. (Ant build expanded it from a jarfile at build time; simpler, I think, to just check it in flat.)
Should be there now.

**Comment by jkesselm** [comment]
(FWIW, I decompiled stylebook to take a quick look at it.  About 2500 lines of code, mostly straightforward.  Almost tempted to comment it and re-contribute it to Apache, if real source can't be found. "In my copious spare time.")

**Comment by slawekjaranowski** [comment]
In `StyleBook` there is code:

```java

    public static void main(String[] var0) throws IOException {
      .....
      exit((String)"All done successfully", 0);
    }

    private static void exit(String var0, int var1) {
        log(var0);
        System.exit(var1);
    }
```

as exec-maven-plugin simply execute code in the same JVM .... in this case build are finished by `System.exit` ....

I have:

```
[INFO] --- exec:3.1.0:java (Stylebook XSLTC documentation) @ xalan-project ---
[StyleBook] Overriding loaderConfig="sbk:/style/loaderdesign.xml" (Old="sbk:/style/loader.xml")
[StyleBook] Overriding targetDirectory="./target/tmp/site/xsltc/" (Old=".")

....

[StyleBook] All done successfully
$
```

**Comment by jkesselm** [comment]
Ah. So `System.exit()` is blowing up the entire Maven session before it can get to the second execution?

If so, the quick fix would be as discussed in https://www.mojohaus.org/exec-maven-plugin/examples/example-exec-for-java-programs.html to launch each StyleBook in a separate JVM.  I'll try that.

(The better fix would be to have a version of StyleBook that doesn't gratuitously call `System.exit()`, of course.)

Thanks. I generally start by assuming I did something stupid... and arguably I did, just not what I thought I had.

**Comment by slawekjaranowski** [comment]
> Ah. So `System.exit()` is blowing up the entire Maven session before it can get to the second execution?

exactly

**Comment by jkesselm** [comment]
Seems to have done it. Thanks!

**Comment by kriegaex** [comment]
@slawekjaranowski, would you be interested in a PR to address this? I thought about an option for the `exec:java` goal to block `System.exit` by means of a security manager (SM). That is deprecated for removal since JDK 17, but still possible, if the Maven JVM is called with `-Djava.security.manager=allow`. The SM would intercept calls to `System.exit` and throw a `SecurityException`, as required by the SM API. The caller (Maven Exec) would handle the exception gracefully and in case of exit code 0 just print an info or debug message to the console or fail the build. That way, users would not be forced to use `exec:exec` in order to fork and could stay within the comfortable bounds of `exec:java` even for tools behaving badly, trying to exit the VM instead of just throwing uncaught exceptions.

Before you refuse because I suggest a deprecated API, please consider that https://openjdk.org/jeps/411 links to https://bugs.openjdk.org/browse/JDK-8199704, which is blocking removal of the SM API until a suitable replacement has been introduced to the JVM, i.e. even in the future there will be a means to block `System.exit`, and Maven Exec can be updated to use that new API, when available and running on a JDK containing such API.

WDYT? Feel free to also mention other MojoHaus developers to discuss this.

**Comment by slawekjaranowski** [comment]
@kriegaex sounds reasonable - we can try with such feature, I have no objections for such PR.

**Comment by kriegaex** [comment]
@jkesselm, feel free to test your project against my PR. That would spare you the effort to use `exec:exec` in the future, i.e. as soon as a plugin release containing this change would be available.

**Comment by kriegaex** [comment]
@slawekjaranowski, do you have any indicator for @jkesselm when a plugin release containing the now merged feature might become available? I actually do not need it myself, but Joseph's use case was so interesting that I decided to implement it for his future use in Xalan-Java, which currently he is so heroically porting from Ant to Maven.

**Comment by slawekjaranowski** [comment]
@kriegaex , @jkesselm - I will release next version in a few days ... maybe in this weekend.

I always like to check topic like site generation, broken links and other simple issue before release

**Comment by jkesselm** [comment]
No rush; the workaround of running in separate processes is fine for now, since we know what's happening. It's more a matter of making things less surprising for the next person with similar needs than anything else, I think.


--
   /_  Joe Kesselman (he/him/his)
-/ _) My Alexa skill for New Music/New Sounds fans:
   /   https://www.amazon.com/dp/B09WJ3H657/

() Plaintext Ribbon Campaign
/\ Stamp out HTML mail!
________________________________
