### ISSUE TITLE
Plugin Seems to Overwrite java.wt.headless with true

### ISSUE THREAD

**Issue by tmiddlet2666** [mojohaus/exec-maven-plugin#40]
I have the following configuration snippet as i want to run a GUI via this plugin.

            <configuration>
              <executable>java</executable>
              <arguments>
                <argument>-classpath</argument>
                <classpath />
                <argument>-Djava.awt.headless=false</argument>
               <argument>MyGUI</argument>

But when i start i get 
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)

Using jvisualvm i look and the system properties says java.awt.headless=true even though i have set as argument.

Any ideas, thanks.
Tim

**Comment by khmarbaise** [comment]
Are you sure you don't have set headless in `JAVA_OPTS` environment variable?

**Comment by tmiddlet2666** [comment]
Hi
Thanks for your reply. Sorry this was an error in the code i was running which was changing it.
All working now thanks.
Tim

**Comment by khmarbaise** [comment]
No Problem. appreciate that i can help we solved the probem.
