### ISSUE TITLE
Define exit code to match

### ISSUE THREAD

**Issue by hvmonteiro** [mojohaus/exec-maven-plugin#41]
It should be very useful if we could define a custom exit code that would be matched when the external command exited, breaking or "making" the build.
Example of a possible plugin configuration
```
          <plugin>
                <artifactId>exec-maven-plugin</artifactId>
                <groupId>org.codehaus.mojo</groupId>
                <executions>
                    <execution>
                        <!-- Run our version calculation script -->
                        <id>Version Calculation</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>grep</executable>
                            <workingDirectory>${project.build.outputDirectory}</workingDirectory>
                            <arguments>
                                <argument>-q -R somestring *</argument>
                             </arguments>
                             <exitCode>1</exitCode>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
This would mean that, if grep didn't find the string 'somestring' the build would succeed, even if grep's exit code is '1' because, well exitCode=1 matches grep's exit code.

-
With the current usage, the build only succeeds if grep exits with '0'. You can't work around that, unless you create a shell script to execute grep and invert the exit code.

Maybe there's a workaround this (besides the shell script) that can give the result I'm after, that I don't know about.

**Comment by khmarbaise** [comment]
Have you check http://www.mojohaus.org/exec-maven-plugin/exec-mojo.html#successCodes ?

**Comment by khmarbaise** [comment]
Unfortunately no feedback so i close the issue
