### ISSUE TITLE
1.5.0. jar corrupt

### ISSUE THREAD

**Issue by ealsedewilde** [mojohaus/exec-maven-plugin#43]
[ERROR] Failed to parse plugin descriptor for org.codehaus.mojo:exec-maven-plugin:1.5.0

When I manually download the jar from http://mvnrepository.com/ and try to open it with 7zip it fails to open, so the file is really corrupt

**Comment by khmarbaise** [comment]
You should download it from Maven Central http://repo1.maven.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.5.0/ and if you are searching for artifacts use https://search.maven.org ...
