### ISSUE TITLE
WARN healenium - Failed to check class: org.codehaus.mojo.exec.ExecJavaMojo$1

### ISSUE THREAD

**Issue by PadmaBhuma** [mojohaus/exec-maven-plugin#453]
Java Version : 17
Exec Maven Plugin : 3.1.0
Apache maven : 3.6.3

I have created a simple maven project with selenium with internal framework and trying to run in the jenkins agents, at that time i am getting this type of logs, But in my local system i am not getting any logs strangely.

13:18:26 2024-10-09 03:48.26 [com.ge.capital.rainbow.testng.run.Runner.main()] WARN  healenium - Failed to check class: org.codehaus.mojo.exec.ExecJavaMojo$1
13:18:26 2024-10-09 03:48.26 [com.ge.capital.rainbow.testng.run.Runner.main()] WARN  healenium - Failed to check class: org.codehaus.mojo.exec.ExecJavaMojo$1
13:18:27 2024-10-09 03:48.27 [com.ge.capital.rainbow.testng.run.Runner.main()] WARN  healenium - Failed to check class: org.codehaus.mojo.exec.ExecJavaMojo$1
13:18:45 2024-10-09 03:48.45 [com.ge.capital.rainbow.testng.run.Runner.main()] WARN  healenium - Failed to check class: org.codehaus.mojo.exec.ExecJavaMojo$1
13:18:58 2024-10-09 03:48.58 [com.ge.capital.rainbow.testng.run.Runner.main()] WARN  healenium - Failed to check class: org.codehaus.mojo.exec.ExecJavaMojo$1
13:18:58 2024-10-09 03:48.58 [com.ge.capital.rainbow.testng.run.Runner.main()] WARN  healenium - Failed to check class: org.codehaus.mojo.exec.ExecJavaMojo$1
13:18:59 2024-10-09 03:48.59 [com.ge.capital.rainbow.testng.run.Runner.main()] WARN  healenium - Failed to check class: org.codehaus.mojo.exec.ExecJavaMojo$1
13:18:59 2024-10-09 03:48.59 [com.ge.capital.rainbow.testng.run.Runner.main()] WARN  healenium - Failed to check class: org.codehaus.mojo.exec.ExecJavaMojo$1
13:18:59 2024-10-09 03:48.59 [com.ge.capital.rainbow.testng.run.Runner.main()] WARN  healenium - Failed to check class: org.codehaus.mojo.exec.ExecJavaMojo$1

Versions using in POM.xml 

Selenium : 4.24.0
Xerces : 2.11.0
Healenium : 3.5.3
allure-testng : 2.13.8

<build>
		<plugins>
			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>clean-allure-results</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
						<configuration>
							<filesets>
								<fileset>
									<directory>allure-results</directory>
									<includes>
										<include>**/*</include>
									</includes>
								</fileset>
							</filesets>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.1.1</version>
				<executions>
					<execution>
						<id>selenium-test</id>
						<phase>test</phase>
						<goals>
							<goal>java</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<skip>${maven.exec.skip}</skip>
					<mainClass>com.ge.capital.rainbow.testng.run.Runner</mainClass>
					<classpathScope>test</classpathScope>
					<arguments>
						<argument>build=3</argument>
						<argument>waitTime=${waitTime}</argument>
						<argument>browser=${browser}</argument>
						<argument>applicationURL=${applicationURL}</argument>
						<argument>application2URL=${application2URL}</argument>
						<argument>MainURL=${mainURL}</argument>
						<argument>username=${username}</argument>
						<argument>suite-template=${suite-template}</argument>
						<argument>print=true</argument>
						<argument>suite-name-parameter=browser</argument>
						<argument>suite-name-parameter=applicationURL</argument>
						<argument>suite-name-parameter=username</argument>
						<argument>suite-strategy=Sequential</argument>
						<argument>runner_single=true</argument>
					</arguments>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.12.4</version>
				<configuration>
					<skipTests>true</skipTests>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by slawekjaranowski** [comment]
We need a simple project to reproduce it ... without external dependencies if possible.

But looks like external tool `com.ge.capital.rainbow.testng.run.Runner` has a problem with `ExecJavaMojo$1` ananymous class ... so should be reported to rainbow project.

**Comment by PadmaBhuma** [comment]
Hi @slawekjaranowski . Actually we have integrated healenium in our internal project ( selenium , Testng, POM ) . in that we are just using our internal runner **com.ge.capital.rainbow.testng.run.Runner** instead of like this
        <configuration>
                    <mainClass>demo.java</mainClass>
        </configuration>

It doesn't have any issue. the thing i found on healenium code is those errors are coming from healenium but i am not aware why it is throwing. can you pls help me on this. 
https://github.com/healenium/healenium-web/blob/master/src/main/java/com/epam/healenium/utils/StackUtils.java
![image](https://github.com/user-attachments/assets/c159080c-2b1f-487e-809a-4ceffd05a847)

**Comment by slawekjaranowski** [comment]
There is similar issue https://github.com/healenium/healenium-web/issues/284

@PadmaBhuma when you report the same issue in multiple project you should mention it.

**Comment by PadmaBhuma** [comment]
As i am not aware of which dependency is throwing the error, I decided to raise on both projects hoping to get the answer from any one end. 

If found any solution, please let me know

**Comment by PadmaBhuma** [comment]
Found the solution , 

I had removed pdfcompare dependency from my project and build it. 


<dependency>
    <groupId>de.redsix</groupId>
    <artifactId>pdfcompare</artifactId>
    <version>1.1.40</version>
    <scope>test</scope>
</dependency>
