### ISSUE TITLE
Execution of powershell.exe

### ISSUE THREAD

**Issue by LaurentTardif** [mojohaus/exec-maven-plugin#48]
When executing powershell.exe on windows, the plugin is frozen. Looks like the powershell process is waiting for an input in the StdIn Stream.

A simple workaround is to send an empty input file in the StdIn by adding an additional parameter in the parameter in the command line (  < emptyFile.txt) .

A simple way to fix that, is to send a fake input in the stdIn stream for powershell.

**Comment by khmarbaise** [comment]
As far as i know you can simply call powershell.exe with a command `powershell -Command "Whatever Command"` just calling powershell.exe will do what you requested ....

**Comment by LucaMerello** [comment]
I've this issue too, using this configuration:

<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>1.5.0</version>
    <executions>
        <execution>
            <id>Copy version on sonar-project.properties file</id>
            <goals>
                <goal>exec</goal>
            </goals>
            <phase>install</phase>
            <configuration>
                <workingDirectory>${project.basedir}</workingDirectory>
                <executable>PowerShell</executable>
                <arguments>
                    <argument>-Command</argument>
                    <argument>"(Get-Content sonar-project.properties) -replace 'sonar.projectVersion=.*', 'sonar.projectVersion=${project.version}.${svn.committedRevision}' | Set-Content sonar-project.properties"</argument>
                </arguments>
            </configuration>
        </execution>
    </executions>
</plugin>

The task is accomplished (hence the sonar.projectVersion field value in sonar-project.properties file is replaced with correct project version number) but maven plugin freeze and I have to kill the process.
I've tried to append " < nul " or " < empty-file.txt " at the end of the command line, following the advice of LaurentTardif, but it doesn't work for me.

Any updates on this issue? Could you please try to replicate the problem at your side? Thanks.

**Comment by LucaMerello** [comment]
I've found an hint by myself, looking at the ticket opened on StackOverflow:
http://stackoverflow.com/questions/2041799/powershell-script-gets-stuck-doesnt-exit-when-called-from-batch-file

Among all the possible solutions proposed, one is simple and effective. It seems that the root of the problem relies on the fact that when PowerShell runs the commands from a script (not from the shell!),  it waits for additional commands from the standard input. If you use the "-InputFormat None" argument to disable the input stream, PowerShell won't get stuck.

Hence, my working configuration is:

```
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.5.0</version>
                <executions>
                    <execution>
                        <id>Copy version on sonar-project.properties file</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <phase>install</phase>
                        <configuration>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <executable>PowerShell.exe</executable>
                            <arguments>
                                <argument>-InputFormat</argument>
                                <argument>None</argument>
                                <argument>-Command</argument>
                                <argument>"(Get-Content sonar-project.properties) -replace 'sonar.projectVersion=.*', 'sonar.projectVersion=${project.version}.${svn.committedRevision}' | Set-Content sonar-project.properties"</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

I think you can close this ticket, since there's nothing wrong within the exec-maven-plugin.

**Comment by khmarbaise** [comment]
Ok. Than I close the ticket. Thanks for the feedback.
