### ISSUE TITLE
Upgrade to Java7

### ISSUE THREAD

**Issue by rfscholte** [mojohaus/exec-maven-plugin#57]

**Comment by TobiX** [comment]
Was that necessary? I have some legacy projects which still require Java 6 to build... This means I would need to continue using my own fork instead of the stock exec-maven-plugin - Can we at least keep Java 6 compatibility for the next release?

**Comment by rfscholte** [comment]
Java7 is the current default for all mojohaus plugins. And we're talking about the runtime, which can be a different version that the JDK you use to build your project. Have a look at https://maven.apache.org/guides/mini/guide-using-toolchains.html to see how you can use different versions for the Maven runtime and the JDK build time.

**Comment by TobiX** [comment]
Ah, sorry. We're already using toolchains. I was under the impression that M2E used the project Java version to call Maven with, but it uses the workspace JDK. Which just means I have to roll out a new Eclipse workspace for my team ;) - Disregard my comment.
