### ISSUE TITLE
Support stream inheritance for the forked process

### ISSUE THREAD

**Issue by gnodet** [mojohaus/exec-maven-plugin#71]
Related to a [jline issue](https://github.com/jline/jline3/issues/77).
Java 7 introduced the ability to inherit standard streams using the [`inheritIO()`](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html#inheritIO()) method.
It would be really nice to be able to support it.

**Comment by gnodet** [comment]
[~olamy] Would you mind having a look at this PR if you have a few minutes ?

**Comment by olamy** [comment]
@gnodet LGTM please do a real pr.  ATM it's only a change in your fork :-)

**Comment by gnodet** [comment]
@olamy The related PR is https://github.com/mojohaus/exec-maven-plugin/pull/72

**Comment by khmarbaise** [comment]
It would be great having an unit or integration test for this?

**Comment by gnodet** [comment]
Fair enough, I'll have a look.

**Comment by gnodet** [comment]
I wrote an integration test, but unfortunately, I don't see a good way to make it work.
The reason is that the way I thought about testing that is to run the `tty` unix command which returns the name of the terminal device. If the `inheritIo` flag works, it should be an existing terminal, else the command returns `not a tty`.  The problem is that this can only work if the maven process actually has a terminal correctly set up (that's the exact problem I'm trying to solve for the exec'ed process here).  So in order for that to work, it would require the maven-invoker-plugin to also be able to inherit  the terminal.  Furthermore, this would also only work if running from a real terminal, so that automated testing in jenkins or such may not work.
