### ISSUE TITLE
NullPointerException with inlcudePluginDependecies=true

### ISSUE THREAD

**Issue by conerck** [mojohaus/exec-maven-plugin#76]
Using mvn 3.3.3
Minimal test case POM (obviously the used dependencies are bogus, but it should be enough to replicate.

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
<groupId>test</groupId>
  <artifactId>PluginDependencies</artifactId>
  <version>0.1-SNAPSHOT</version>  
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>exec-maven-plugin</artifactId>
          <version>1.6.0</version>
          <executions>
            <execution>
              <id>default</id>
              <goals>
                <goal>java</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <executableDependency>
              <groupId>org.codehaus.mojo</groupId>
              <artifactId>exec-maven-plugin</artifactId>
            </executableDependency>
            <includeProjectDependencies>false</includeProjectDependencies>
            <includePluginDependencies>true</includePluginDependencies>
            <mainClass>org.codehaus.mojo.exec.ExecJavaMojo</mainClass>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.mojo</groupId>
              <artifactId>exec-maven-plugin</artifactId>
              <version>1.6.0</version>
              <type>jar</type>
            </dependency>
          </dependencies>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>`

This will fail with
` mvn exec:java
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building PluginDependencies 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ PluginDependencies ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.673 s
[INFO] Finished at: 2017-03-16T11:46:02+01:00
[INFO] Final Memory: 11M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project PluginDependencies: Execution default-cli of goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java failed. NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Picked up _JAVA_OPTIONS: -Xmx2048M

in 1.5.0 this setup worked fine. Obviously with this sample POM the build will still fail because the executableDependency has no mainClass.

**Comment by jmini** [comment]
@JonasRutishauser: I can confirm that the version `1.6.1-SNAPSHOT` built from your [bugfix/NPE-with-includePluginDependencies](https://github.com/JonasRutishauser/exec-maven-plugin/tree/bugfix/NPE-with-includePluginDependencies) branch is also working for me. See my example project on GitHub: https://github.com/jmini/exec-maven-plugin_issue_76

Thank you a lot, I hope this will be merged back in the master.

**Comment by vasiliy-bout** [comment]
Hi, I use instruction from http://www.mojohaus.org/exec-maven-plugin/examples/example-exec-using-plugin-dependencies.html and still get `NullPointerException`. When this fix is going to be merged and released?

**Comment by thinkerou** [comment]
+1

I use `<exec-maven-plugin.version>1.5.0</exec-maven-plugin.version>` it is OK, but use `<exec-maven-plugin.version>1.6.0</exec-maven-plugin.version>` (ONLY Change version) will have the follow error:

`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (generate-scala-protobuf-classes) on project gatling-grpc: Execution generate-scala-protobuf-classes of goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java failed.: NullPointerException -> [Help 1]
[ERROR] `

**Comment by jycr** [comment]
Any news about the resolution of this bug?

**Comment by masu1402** [comment]
Still not resolved? Can't see any new versions and the bug fix is still in an open branch.

**Comment by dwabm** [comment]
is there a merge an release roadmap for tis fix?

**Comment by workcartersmith** [comment]
This is still a thing.
