### ISSUE TITLE
exec:exec async not working

### ISSUE THREAD

**Issue by simonwibberley** [mojohaus/exec-maven-plugin#88]
Hi - I can't get exec:exec to leave the child process running. 

Please see minimal pom executing sleep below, and attached simple printing java program. I can't see what I'm doing wrong! 

Thanks,

Simon

Tested on:
OS X 10.11.6 & Ubuntu 14.04
Apache Maven 3.5.2 & 3.1.something
exec-maven-plugin 1.6.0 & 1.6.1-SNAPSHOT

[async.zip](https://github.com/mojohaus/exec-maven-plugin/files/1437132/async.zip)

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>example</groupId>
  <artifactId>app</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>Maven Quick Start Archetype</name>
  <url>http://maven.apache.org</url>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <async>true</async>
                    <asyncDestroyOnShutdown>false</asyncDestroyOnShutdown>
                    <executable>sleep</executable>
                    <commandlineArgs>20</commandlineArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by robozb** [comment]
At me with async, the external apps don't open as well :(

<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>tomcatmanager-url-open</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <phase/>
                        <configuration>
                            <executable>${default-bongeszo}</executable>
                            <async>true</async>
                            <arguments>
                                <argument>${tomcatmanager-webcim}</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>phpmyadmin-url-open</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <phase/>
                        <configuration>
                            <executable>${default-bongeszo}</executable>
                            <async>true</async>
                            <arguments>
                                <argument>${phpmyadmin-webcim}</argument>
                            </arguments>
                        </configuration>
                    </execution>             
                    <execution>
                        <id>navonlineszamla-teszt-url-open</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <phase/>
                        <configuration>
                            <executable>${ff-bongeszo}</executable>
                            <async>true</async>
                            <arguments>
                                <argument>${navonlineszamla-teszt-webcim}</argument>
                            </arguments>
                        </configuration>
                    </execution>                    
                </executions>                                
            </plugin>

**Comment by pzygielo** [comment]
@simonwibberley - using your (fixed, as it has unopened `</dependencies>`) pom - it works perfectly fine for me:
```
$ ps ; mvn exec:exec ; ps
    PID TTY          TIME CMD
   2720 pts/0    00:00:00 bash
   3349 pts/0    00:00:00 ps
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------------< example:app >-----------------------------
[INFO] Building Maven Quick Start Archetype 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:exec (default-cli) @ app ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.905 s
[INFO] Finished at: 2020-11-14T13:25:44+01:00
[INFO] ------------------------------------------------------------------------
    PID TTY          TIME CMD
   2720 pts/0    00:00:00 bash
   3392 pts/0    00:00:00 sleep
   3395 pts/0    00:00:00 ps
$
```
As you can see - once maven finished - there is extra `sleep` process running.
