### ISSUE TITLE
Regression when longClasspath = true

### ISSUE THREAD

**Issue by aaccioly** [mojohaus/exec-maven-plugin#93]
Hi guys, I think that I've stumbled across a potential regression in release **1.6.0**.

### Working code snippet:

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>1.5.0</version> <!-- Change version to 1.6.0 or 1.6.1-SNAPSHOT -->
    <executions>
        <execution>
            <phase>integration-test</phase>
            <goals>
                <goal>exec</goal>
            </goals>
            <configuration>
                <executable>java</executable>
                <classpathScope>test</classpathScope>
                <longClasspath>true</longClasspath>
                <environmentVariables>
                    <environment>${environment}</environment>
                </environmentVariables>
                <arguments>
                    <argument>-classpath</argument> <!-- First line to comment -->
                    <classpath/>                    <!-- Second line to comment -->
                    <argument>cucumber.api.cli.Main</argument>
                    <argument>--monochrome</argument>
                    <argument>--format</argument>
                    <argument>html:target/cucumber-html-report</argument>
                    <argument>--glue</argument>
                    <argument>com/mycompany/myproject/features</argument>
                    <argument>.</argument>
                </arguments>
            </configuration>
        </execution>
    </executions>
</plugin>
```
#### Version 1.5.0

>[DEBUG] Executing command line: [C:\JDK64\LINKS\CURRENT\bin\java.exe, -jar, C:\Users\myuser\AppData\Local\Temp\maven-exec3498439305955478761.jar, --monochrome, --format, html:target/cucumber-html-report, --glue, com/mycompany/myproject/features .]

#### Version 1.6.0 +

>[DEBUG] Executing command line: [C:\JDK64\LINKS\CURRENT\bin\java.exe, -jar, C:\Users\myuser\AppData\Local\Temp\maven-exec6844626987228641413.jar, **-classpath,** --monochrome, --format, html:target/cucumber-html-report, --glue, com/mycompany/myproject/features , .]
Usage: java cucumber.api.cli.Main [options] [ [FILE|DIR][:LINE[:LINE]*] **]+**

The extra empty `-classpath` argument is breaking Cucumber execution. 

If I comment `<argument>-classpath</argument><classpath/>`  exec-maven-plugin ignores `<longClasspath>true</longClasspath>` and fails to generate a wrapper jar:  

>[DEBUG] Executing command line: [C:\JDK64\LINKS\CURRENT\bin\java.exe, cucumber.api.cli.Main, --monochrome, --format, html:target/cucumber-html-report, --glue, com/jpm/cib/is/vet/ios/cash/features, .]

I need `<longClasspath>true</longClasspath>` in order to avoid `CreateProcess error=206, The filename or extension is too long` on Windows. 

So, at this time, for projects with long Classpath strings I can't really upgrade from version *1.5.0* to *1.6.0+*

**Comment by plcarmel** [comment]
Issue have been reintroduced in 3.0.0 in this commit, specifically:

https://github.com/mojohaus/exec-maven-plugin/commit/137189b56c7166d9e167018add666247f5a68e27

**Comment by plcarmel** [comment]
PR: https://github.com/mojohaus/exec-maven-plugin/pull/228
