### ISSUE TITLE
<modulepath/> option doesn't work for multi-module project

### ISSUE THREAD

**Issue by gunnarmorling** [mojohaus/exec-maven-plugin#98]
In `ExecMavenMojo`, it tries to create the file for the module path always under _target/modulepath_. This doesn't work if invoked from the root of a multi-module build for one of the modules (it'd have to be _%mymodule%/target/modulepath_ then), and also fails if the user has configured another directory than _target_ as their build directory.

I'll send a PR in a bit.

**Comment by gunnarmorling** [comment]
PR is here: https://github.com/mojohaus/exec-maven-plugin/pull/99

**Comment by abierfert** [comment]
Any word on this? I just stumbled across this in my project while migrating to jdk11/jigsaw. Calling from the module builds work find, calling from the parent builds fail as described.

Is there a viable workaround (other than building the module on its own)?

**Comment by rfscholte** [comment]
Can you create an integration-test for this, just to be sure #99 is all you need.
